version: '2.2'
services:
  host:
    image: ubuntu
    privileged: true
    entrypoint:
      - "sleep"
      - "inf"
    volumes:
      - /:/rootfs
  memtiera:
    hostname: memtiera
    build: images/memtier_benchmark
    cpuset: 2,3,6,7
    links:
      - redisa
      - influxdb
  redisa:
    image: memcached:latest
    command: [ "memcached" , "-m", "2048" ]
    cpuset: 2,3,6,7
    cgroup_parent: consolidate
    mem_limit: 2G
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '54mb'
      device_write_bps:
        - path: /dev/sda
          rate: '54mb'
  memtierb:
    hostname: memtierb
    build: images/memtier_benchmark
    cpuset: 0,4,1,5
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '54mb'
      device_write_bps:
        - path: /dev/sda
          rate: '54mb'
    links:
      - redisa
      - influxdb
  redisb:
    image: memcached:latest
    command: [ "memcached" , "-m", "2048" ]
    cpuset: 0,4,1,5
    cgroup_parent: consolidate
    mem_limit: 2G
  cassandra:
    build: images/cassandra
    cgroup_parent: consolidate
    mem_limit: 2516901888
    mem_swappiness: 0
    cpuset: 0,4,1,5
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '54mb'
      device_write_bps:
        - path: /dev/sda
          rate: '54mb'
  influxdb:
    image: influxdb:latest
  collector:
    build: images/collector
    command: [ "--influx", "--influxdbhost=influxdb", "--influxdbname=acdc" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb
  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    volumes:
      - data-grafana-var-lib:/var/lib/grafana
      - data-grafana-var-log:/var/log/grafana
      - data-grafana-etc:/etc/grafana
    links:
      - influxdb
volumes:
  data-grafana-var-lib:
  data-grafana-var-log:
  data-grafana-etc:
