#!/bin/bash
set -e -x

CGROUP=$1
SLEEP=$2

while sleep ${SLEEP}
do
	i=0
	find "${CGROUP}" -name 'memory.priority' | while read cg
	do
		cg=$(dirname $cg)
		recent_rotated_anon=$(grep recent_rotated_anon $cg/memory.stat | cut -d ' '  -f2)
		recent_scanned_anon=$(grep recent_scanned_anon $cg/memory.stat | cut -d ' '  -f2)
		recent_rotated_file=$(grep recent_rotated_file $cg/memory.stat | cut -d ' '  -f2)
		recent_scanned_file=$(grep recent_scanned_file $cg/memory.stat | cut -d ' '  -f2)
		recent_ratio_total=$((recent_scanned_anon + recent_scanned_file) / (1+recent_rotated_anon+recent_rotated_file))
		echo "${recent_ratio_total} ${cg}"
	done | sort -n | cut -d ' ' -f2 | while read cg
	do
		echo $i > ${cg}/memory.priority
		i=$((i+1))
	done
done
