version: '2.2'
services:
  host:
    image: ubuntu
    privileged: true
    entrypoint:
      - "sleep"
      - "inf"
    volumes:
      - /:/rootfs
  sysbencha:
    build: images/sysbench
    command: [ '--mysql-hostname=mysqla', 'mysql-dbname=dbname' ]
    links:
      - mysqla:mysqla
      - influxdb
    cpuset: 0,4,1,5
  sysbenchb:
    build: images/sysbench
    command: [ '--mysql-hostname=mysqlb', 'mysql-dbname=dbnameb' ]
    links:
      - mysqla:mysqlb
      - influxdb
    cpuset: 0,4,1,5
  sysbenchc:
    build: images/sysbench
    links:
      - mysqlc:mysql
      - influxdb
    cpuset: 0,4,1,5
  mysqla:
    build: images/mysql
    hostname: mysqla
    volumes:
      - data-mysqla:/var/lib/mysql
    cgroup_parent: 'consolidate/A'
    cpuset: '2'
    cpus: 1
  mysqlb:
    build: images/mysql
    hostname: mysqlb
    volumes:
      - data-mysqlb:/var/lib/mysql
    cgroup_parent: 'consolidate/BC/B'
    cpuset: '2'
    cpus: 1
  mysqlc:
    build: images/mysql
    hostname: mysqlc
    volumes:
      - data-mysqlc:/var/lib/mysql
    cgroup_parent: 'consolidate/BC/C'
    cpuset: 2,6
    cpus: 1
  influxdb:
    image: influxdb:latest
  collector:
    build: images/collector
    command: [ "--influx", "--influxdbhost=influxdb", "--influxdbname=acdc" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb
  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    volumes:
      - data-grafana-var-lib:/var/lib/grafana
      - data-grafana-var-log:/var/log/grafana
      - data-grafana-etc:/etc/grafana
    links:
      - influxdb
volumes:
  data-mysqla:
    external: true
  data-mysqlb:
    external: true
  data-mysqlc:
    external: true
  data-grafana-var-lib:
  data-grafana-var-log:
  data-grafana-etc:
