version: '2.2'
services:
  host:
    image: ubuntu
    privileged: true
    entrypoint:
      - "sleep"
      - "inf"
    volumes:
      - /:/rootfs
  sysbencha:
    build: images/sysbench
    cpuset: 2,3,6,7
    links:
      - mysqla:mysql
      - influxdb
  sysbenchb:
    build: images/sysbench
    cpuset: 0,4,1,5
    links:
      - mysqlb:mysql
      - influxdb
  mysqla:
    build: images/mysql
    hostname: mysqla
    volumes:
      - data-mysqla:/var/lib/mysql
    cgroup_parent: consolidate
    mem_limit: 1G
    cpuset: 2,3,6,7
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '27mb'
      device_write_bps:
        - path: /dev/sda
          rate: '27mb'
  mysqlb:
    build: images/mysql
    hostname: mysqlb
    volumes:
      - data-mysqlb:/var/lib/mysql
    cgroup_parent: consolidate
    mem_limit: 1G
    cpuset: 0,4,1,5
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '27mb'
      device_write_bps:
        - path: /dev/sda
          rate: '27mb'
  cassandra:
    build: images/cassandra
    cgroup_parent: consolidate
    mem_limit: 2516901888
    mem_swappiness: 0
    cpuset: 0,4,1,5
    blkio_config:
      device_read_bps:
        - path: /dev/sda
          rate: '27mb'
      device_write_bps:
        - path: /dev/sda
          rate: '27mb'
  influxdb:
    image: influxdb:latest
  collector:
    build: images/collector
    command: [ "--influx", "--influxdbhost=influxdb", "--influxdbname=acdc" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb
  idlememstat:
    build: images/idlememstat
    privileged: true
    command: [ "-d", "10", "--influxdbhost", "influxdb", "--updateMemoryPriority", "--cgroup", "/rootfs/sys/fs/cgroup/memory/consolidate" ]
    environment:
      - KPAGEFLAGS_PATH=/rootfs/proc/kpageflags
      - KPAGECGROUP_PATH=/rootfs/proc/kpagecgroup
      - KPAGEIDLE_PATH=/rootfs/sys/kernel/mm/page_idle/bitmap
      - MEMCG_ROOT_PATH=/rootfs/sys/fs/cgroup/memory
      - ZONE_INFO_PATH=/rootfs/proc/zoneinfo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/zoneinfo:/rootfs/proc/zoneinfo
      - /proc/kpageflags:/rootfs/proc/kpageflags
      - /proc/kpagecgroup:/rootfs/proc/kpagecgroup
      - /sys/kernel/mm/page_idle/bitmap:/rootfs/sys/kernel/mm/page_idle/bitmap
      - /sys/fs/cgroup/memory:/rootfs/sys/fs/cgroup/memory
    links:
      - influxdb
  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    volumes:
      - data-grafana-var-lib:/var/lib/grafana
      - data-grafana-var-log:/var/log/grafana
      - data-grafana-etc:/etc/grafana
    links:
      - influxdb
volumes:
  data-mysqla:
    external: true
  data-mysqlb:
    external: true
  data-grafana-var-lib:
  data-grafana-var-log:
  data-grafana-etc:
