version: "2.0"
services:
  fincore:
    build: .
    links:
      - influxdb
  influxdb:
    image: influxdb:latest
  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    links:
      - influxdb
